---
- name: Configure backup
  ansible.builtin.template:
    src: backup-mysql.jinja2
    dest: /etc/oxiscripts/jobs/backup-mysql.sh
    owner: root
    group: root
    mode: "0740"
  become: true
  become_user: root

- name: Enable mysql-backup
  ansible.builtin.file:
    src: /etc/oxiscripts/jobs/backup-mysql.sh
    dest: /etc/cron.daily/backup-mysql
    owner: root
    group: root
    state: link
  become: true
  become_user: root
